server:
  context-path: /auth
  port: 5000

management:
  context-path: /mgmt

eureka:
  instance:
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
      management:
        context-path: /actuator
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
    home-page-url: http://localhost:${server.port}/

spring:
  datasource:
    url: jdbc:h2:mem:user
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
security:
  user:
    name: user
    password: ${CONFIG_SERVER_PASSWORD:password}